
/*
 * Copyright (C) 2007-2019 Crafter Software Corporation. All Rights Reserved.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

// State: the particular condition that someone or something is in at a specific time.
// Status: the situation at a particular time during a *process.*

export enum WorkflowStatusEnum {

  UNKNOWN = 'UNKNOWN',

  NEW_UNPUBLISHED_LOCKED = 'NEW_UNPUBLISHED_LOCKED',
  NEW_UNPUBLISHED_UNLOCKED = 'NEW_UNPUBLISHED_UNLOCKED',
  NEW_SUBMITTED_WITH_WF_SCHEDULED = 'NEW_SUBMITTED_WITH_WF_SCHEDULED',
  NEW_SUBMITTED_WITH_WF_SCHEDULED_LOCKED = 'NEW_SUBMITTED_WITH_WF_SCHEDULED_LOCKED',
  NEW_SUBMITTED_WITH_WF_UNSCHEDULED = 'NEW_SUBMITTED_WITH_WF_UNSCHEDULED',
  NEW_SUBMITTED_WITH_WF_UNSCHEDULED_LOCKED = 'NEW_SUBMITTED_WITH_WF_UNSCHEDULED_LOCKED',
  NEW_SUBMITTED_NO_WF_SCHEDULED = 'NEW_SUBMITTED_NO_WF_SCHEDULED',
  NEW_SUBMITTED_NO_WF_SCHEDULED_LOCKED = 'NEW_SUBMITTED_NO_WF_SCHEDULED_LOCKED',
  NEW_SUBMITTED_NO_WF_UNSCHEDULED = 'NEW_SUBMITTED_NO_WF_UNSCHEDULED', // waiting in the queue, will be published any moment
  NEW_PUBLISHING_FAILED = 'NEW_PUBLISHING_FAILED',
  NEW_DELETED = 'NEW_DELETED',

  EXISTING_UNEDITED_LOCKED = 'EXISTING_UNEDITED_LOCKED',
  EXISTING_UNEDITED_UNLOCKED = 'EXISTING_UNEDITED_UNLOCKED',
  EXISTING_EDITED_LOCKED = 'EXISTING_EDITED_LOCKED',
  EXISTING_EDITED_UNLOCKED = 'EXISTING_EDITED_UNLOCKED',
  EXISTING_SUBMITTED_WITH_WF_SCHEDULED = 'EXISTING_SUBMITTED_WITH_WF_SCHEDULED',
  EXISTING_SUBMITTED_WITH_WF_SCHEDULED_LOCKED = 'EXISTING_SUBMITTED_WITH_WF_SCHEDULED_LOCKED',
  EXISTING_SUBMITTED_WITH_WF_UNSCHEDULED = 'EXISTING_SUBMITTED_WITH_WF_UNSCHEDULED',
  EXISTING_SUBMITTED_WITH_WF_UNSCHEDULED_LOCKED = 'EXISTING_SUBMITTED_WITH_WF_UNSCHEDULED_LOCKED',
  EXISTING_SUBMITTED_NO_WF_SCHEDULED = 'EXISTING_SUBMITTED_NO_WF_SCHEDULED',
  EXISTING_SUBMITTED_NO_WF_SCHEDULED_LOCKED = 'EXISTING_SUBMITTED_NO_WF_SCHEDULED_LOCKED',
  EXISTING_SUBMITTED_NO_WF_UNSCHEDULED = 'EXISTING_SUBMITTED_NO_WF_UNSCHEDULED',
  EXISTING_PUBLISHING_FAILED = 'EXISTING_PUBLISHING_FAILED',
  EXISTING_DELETED = 'EXISTING_DELETED'

}
